# Generated by Django 4.1.7 on 2023-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='subtitulo',
            field=models.CharField(default='', max_length=140),
        ),
    ]
