# Generated by Django 4.1.7 on 2023-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articulos_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
