# Generated by Django 4.1.7 on 2023-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_articulos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articulos',
            name='cuerpo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
